SomeRentalBusiness/src/WebApp/Controllers/BikeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Domain.Commands;
using Domain.Commands.Contexts;
using Domain.Entities;
using Domain.Entities.Deposits;
using Domain.Queries.Criteria;
using Infrastructure.Queries;
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers
{
    public class BikeController : Controller
    {
        private readonly IQueryBuilder _queryBuilder;
        private readonly ICommandBuilder _commandBuilder;

        public BikeController(IQueryBuilder queryBuilder,ICommandBuilder commandBuilder)
        {
            _queryBuilder = queryBuilder;
            _commandBuilder = commandBuilder;
        }
        // GET: /<controller>/
        public IActionResult View(string name)
        {
            Bike bike = _queryBuilder.For<Bike>().With(new NameCriterion()
            {
                Name = name
            });
            return View(bike);
        }

        public IActionResult Take(string name,string surname,string firstName, string patronymic,decimal money)
        {
            AddClientCommandContext clientCommandContext=new AddClientCommandContext()
            {
                FirstName = firstName,
                Surname = surname,
                Patronymic = patronymic
            };
            _commandBuilder.Execute(clientCommandContext);
            MoneyDeposit deposit=new MoneyDeposit(money);
            Bike bike = _queryBuilder.For<Bike>().With(new NameCriterion()
            {
                Name = name
            });
            _commandBuilder.Execute(new GetBikeInRentCommandContext()
            {
                Bike = bike,
                Client = clientCommandContext.CreatedClient,
                Deposit = deposit
            });
            ViewData["Message"] = string.Format("{0} взял в прокат {1} и отдал в качестве депозита {2} рублей",
                clientCommandContext.CreatedClient.FullName, name, money.ToString());
            return View();
        }

        public IActionResult ReturnBikePage()
        {
            return View();
        }

        public IActionResult Return(string bikeName, string rentPointName)
        {
            RentPoint rentPoint = _queryBuilder.For<RentPoint>().With(new NameCriterion()
            {
                Name = rentPointName
            });
            Bike bike = _queryBuilder.For<Bike>().With(new NameCriterion()
            {
                Name = bikeName
            });
            _commandBuilder.Execute(new ReturnBikeCommandContext()
            {
                Bike = bike,
                RentPoint = rentPoint,
                IsBroken = false
            });
            return View();
        }
    }
}

SomeRentalBusiness/src/WebApp/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Domain.Commands;
using Domain.Commands.Contexts;
using Infrastructure.Queries;
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IQueryBuilder _queryBuilder;
        private readonly ICommandBuilder _commandBuilder;

        public EmployeeController(IQueryBuilder queryBuilder,ICommandBuilder commandBuilder)
        {
            _queryBuilder = queryBuilder;
            _commandBuilder = commandBuilder;
        }
        // GET: /<controller>/
        [HttpPost]
        public IActionResult Add(string surname, string firstname, string patronymic)
        {
            _commandBuilder
                .Execute(new AddEmployeeCommandContext()
                {
                    FirstName = firstname,
                    Surname = surname,
                    Patronymic = patronymic
                });
            ViewBag.Message = string.Format("Работник {0} {1} {2} успешно добавлен.",surname,firstname,patronymic);
            return View();
        }
        
        public IActionResult AddEmployeeIndex()
        {
            return View();
        }
    }
}

SomeRentalBusiness/src/WebApp/Controllers/RentPointController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Domain.Commands;
using Domain.Commands.Contexts;
using Domain.Entities;
using Domain.Queries.Criteria;
using Infrastructure.Queries;
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers
{
    public class RentPointController : Controller
    {
        private readonly IQueryBuilder _queryBuilder;
        private readonly ICommandBuilder _commandBuilder;
        // GET: /<controller>/
        public RentPointController(IQueryBuilder queryBuilder, ICommandBuilder commandBuilder)
        {
            _queryBuilder = queryBuilder;
            _commandBuilder = commandBuilder;
            if (!_queryBuilder.For<IEnumerable<RentPoint>>().With(new EmptyCriterion()).Any())
            {
                AddEmployeeCommandContext employeeContext = new AddEmployeeCommandContext()
                {
                    Surname = "Ivanov",
                    FirstName = "Ivan",
                    Patronymic = "Ivanovich"
                };
                _commandBuilder.Execute(employeeContext);
                AddRentPointCommandContext komprosRentPointContext = new AddRentPointCommandContext()
                {
                    Name = "Компрос",
                    Employee = employeeContext.CreatedEmployee,
                    Money = 10000
                };
                _commandBuilder.Execute(komprosRentPointContext);
                AddRentPointCommandContext leninaRentPointContext = new AddRentPointCommandContext()
                {
                    Name = "Ленина",
                    Employee = employeeContext.CreatedEmployee,
                    Money = 10000
                };
                _commandBuilder.Execute(leninaRentPointContext);
                _commandBuilder.Execute(new AddBikeCommandContext()
                {
                    Name = "Kama",
                    Cost = 1000,
                    HourCost = 100,
                    RentPoint = komprosRentPointContext.CreatedRentPoint
                });
                _commandBuilder.Execute(new AddBikeCommandContext()
                {
                    Name = "Stels",
                    Cost = 1000,
                    HourCost = 100,
                    RentPoint = komprosRentPointContext.CreatedRentPoint
                });
                _commandBuilder.Execute(new AddBikeCommandContext()
                {
                    Name = "Forward",
                    Cost = 1000,
                    HourCost = 100,
                    RentPoint = komprosRentPointContext.CreatedRentPoint
                });
                _commandBuilder.Execute(new AddBikeCommandContext()
                {
                    Name = "Lexus134",
                    Cost = 1000,
                    HourCost = 100,
                    RentPoint = leninaRentPointContext.CreatedRentPoint
                });
            }
        }
        public IActionResult Add(string name,string surname,string firstname,string patronymic,decimal money)
        {
            AddEmployeeCommandContext employeeCommandContext=new AddEmployeeCommandContext()
            {
                Surname = surname,
                FirstName = firstname,
                Patronymic = patronymic
            };
            _commandBuilder.Execute(employeeCommandContext);
            _commandBuilder.Execute(new AddRentPointCommandContext()
            {
                Name=name,
                Employee = employeeCommandContext.CreatedEmployee,
                Money = money
            });
            ViewBag.Message = string.Format("Точка проката {0} успешно добавлена", name);
            return View();
        }

        public IActionResult List()
        {
            IEnumerable<RentPoint> listRentPoints = 
                _queryBuilder
                .For<IEnumerable<RentPoint>>()
                .With(new EmptyCriterion());
            return View(listRentPoints);
        }

        public IActionResult View(string name)
        {
            RentPoint rentPoint = _queryBuilder.For<RentPoint>().With(new NameCriterion()
            {
                Name = name
            });
            return View(rentPoint);
        }

        public IActionResult AddRentPointIndex()
        {
            return View();
        }

        public IActionResult GetAllBikesOnRentPoint(string name)
        {
            RentPoint rentPoint = _queryBuilder.For<RentPoint>().With(new NameCriterion()
            {
                Name = name
            });
            IEnumerable<Bike> listBikes = _queryBuilder.For<IEnumerable<Bike>>().With(new RentPointCriterion()
            {
                RentPoint = rentPoint
            });
            ViewData["Message"] = string.Format("Байки с точки проката {0}", name);
            return View(listBikes);
        }
    }
}

SomeRentalBusiness/src/WebApp/Views/Shared/_Layout.cshtml
@using Microsoft.ApplicationInsights.Extensibility
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">RentalBusiness</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="~/RentPoints">Все точки проката</a></li>
                    <li><a asp-area="" asp-controller="Employee" asp-action="AddEmployeeIndex">Добавить сотрудника</a></li>
                    <li><a asp-area="" asp-controller="RentPoint" asp-action="AddRentPointIndex">Добавить точку проката</a></li>
                    <li><a asp-area="" asp-controller="Bike" asp-action="ReturnBikePage">Вернуть байк</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - WebApp</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>